#! /bin/bash
SCRIPT=`basename ${BASH_SOURCE[0]}`
ARGS=("$@")

# Print usage and exit
function USAGE {
  echo -e "\nOpen Reading List. Usage: $SCRIPT 'topic'"
  echo -e "Usage: $SCRIPT 'topic'"
  echo -e "\nOpen all the documents on a specified topic in a given reading list"
  echo -e "(created, for example, by the companion 'rlc' script)."
  echo -e "\nThe input is a series of comma separated value (CSV) lines read from standard"
  echo -e "input consisting of a topic tag and absolute path to a document/file."
  echo -e "\nOptions recognized::"
  echo -e "-a -- The application name (default: Preview)"
  echo -e "-f -- Read input from named file (default: STDIN)"
  echo -e "\nAll remaining positional (non-option) parameters are concatenated (joined with"
  echo -e "a blank separator) and used as the reading list topic tag (default: 'ReadLater')\n"
  exit 1
}

# Option defaults
APP="Preview"
FILE="STDIN"

# Command line options
while getopts :ha:f: OPT; do
  case $OPT in
    a)
      APP=$OPTARG
      ;;
    f)
      FILE=$OPTARG
      ;;
    h)
      USAGE
      ;;
    \?)
      echo -e "\nInvalid command line option - $OPTARG"
      USAGE
      ;;
  esac
done

# Optionally redirect output and append to specified file
[ "$FILE" != "STDIN" ] && exec < $FILE

# Join remaining command line arguments
IND=$(expr $OPTIND - 1)
REST=("${ARGS[@]:$IND}")
TOPIC=${REST[@]:-"ReadLater"}

# Open files with matching topic tag
FILES=$(grep "^$TOPIC" <&0 | awk '{print $2}')
for FILE in $FILES; do
  open -a $APP $FILE
done
